version: '3'
services:
  redis:
    image: 'redis:6-alpine'
    container_name: test-redis
    ports:
      - "6382:6379"
    networks:
      - test-network
  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9092:9090"
    container_name: test-prometheus
    networks:
      - test-network
networks:
  test-network:
    driver: bridge