hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000
server:
  port: 8080
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
    consul:
      discovery:
        hostname: gateway
        instanceId: gateway
        health-check-path: /actuator/health
        prefer-ip-address: true
      host: localhost
      port: 8500
      enabled: true
  redis:
    port: 6382
    host: localhost
    database: 1
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: gateway
debug: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

