server:
  port: 8081
spring:
  cloud:
    consul:
      discovery:
        hostname: student
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        health-check-path: /actuator/health
        prefer-ip-address: true
      host: localhost
      port: 8500
      enabled: true
  application:
    name: student